// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Wed Mar 25 23:51:53 2026

CONTROL CONTROL_inst
(
	.IBUS(IBUS_sig) ,	// input [31:0] IBUS_sig
	.C(C_sig) ,	// input  C_sig
	.V(V_sig) ,	// input  V_sig
	.N(N_sig) ,	// input  N_sig
	.Z(Z_sig) ,	// input  Z_sig
	.PCSEL(PCSEL_sig) ,	// output [1:0] PCSEL_sig
	.A3SEL(A3SEL_sig) ,	// output  A3SEL_sig
	.ROTSEL(ROTSEL_sig) ,	// output  ROTSEL_sig
	.SHAMTSEL(SHAMTSEL_sig) ,	// output  SHAMTSEL_sig
	.SRC2SEL(SRC2SEL_sig) ,	// output  SRC2SEL_sig
	.REGWR(REGWR_sig) ,	// output  REGWR_sig
	.ALUSEL(ALUSEL_sig) ,	// output [3:0] ALUSEL_sig
	.CPSRWR(CPSRWR_sig) ,	// output [1:0] CPSRWR_sig
	.MEMWR(MEMWR_sig) ,	// output  MEMWR_sig
	.MEMRD(MEMRD_sig) ,	// output  MEMRD_sig
	.WD4SEL(WD4SEL_sig) ,	// output [1:0] WD4SEL_sig
	.A4SEL(A4SEL_sig) 	// output  A4SEL_sig
);

